(module day02b (main main))

(define (prog-usage progname)
    (display (format "usage: ~a <file>" progname))
    (newline)
    (exit))

(define (process filename)
    (let ((result 0))
        (with-input-from-file filename
            (lambda ()
                (let loop ((line (read-line (current-input-port))))
                    (if (not (eof-object? line))
                        (begin
                            (let* ((draws-part (cadr (string-split line ":")))
                                   (red-needed 0)
                                   (green-needed 0)
                                   (blue-needed 0)
                                   (draws (string-split draws-part ";")))
                                (for-each
                                    (lambda (draw)
                                        (let ((color-amounts (string-split draw ",")))
                                            (for-each
                                                (lambda (color-amount)
                                                    (let* ((trimmed-color-amount (substring color-amount 1))
                                                           (amount-str (car (string-split trimmed-color-amount " ")))
                                                           (color (cadr (string-split trimmed-color-amount " ")))
                                                           (amount (string->number amount-str)))
                                                        (cond ((string=? color "red")
                                                                (if (> amount red-needed)
                                                                    (set! red-needed amount)))
                                                              ((string=? color "green")
                                                                (if (> amount green-needed)
                                                                    (set! green-needed amount)))
                                                              ((string=? color "blue")
                                                                (if (> amount blue-needed)
                                                                    (set! blue-needed amount))))))
                                                color-amounts)))
                                    draws)
                                (set! result (+ result (* red-needed green-needed blue-needed))))
                            (loop (read-line (current-input-port))))
                        (close-input-port (current-input-port))))))
        result))

(define (main argv)
    (if (< (length argv) 2)
        (prog-usage (car argv))
        (let* ((filename (cadr argv))
               (result (process filename)))
            (display (format "result = ~a" result))
            (newline))))
