(module day03a (main main))

(define (prog-usage progname)
    (display (format "usage: ~a <file>" progname))
    (newline)
    (exit))

(define (read-file-into-lines filename)
  (call-with-input-file filename
    (lambda (file)
      (let loop ((lines '())
                 (line (read-line file)))
        (if (not (eof-object? line))
            (begin
                (loop (cons line lines) (read-line file))
            )
            (reverse lines))))))

(define (digit-char? ch)
    (and (char-numeric? ch) (not (char=? ch #\.))))

(define (build-numbers lines)
    (let ((number-locs '())
          (row 0)
          (scanning-number #f)
          (number "")
          (current-pos '(-1 -1)))
        (for-each
            (lambda (line)
                (let loop ((col 0))
                    (let ((ch (string-ref line col)))
                        (if scanning-number
                            (if (char-numeric? ch)
                                (set! number (string-append number (string ch)))
                                (begin
                                    (set! number-locs (cons (cons current-pos number) number-locs))
                                    (set! scanning-number #f)
                                    (set! number "")))
                            (if (char-numeric? ch)
                                (begin
                                    (set! number (string ch))
                                    (set! current-pos `(,row ,col))
                                    (set! scanning-number #t))))
                        (if (< (+ 1 col) (string-length line))
                            (loop (+ 1 col)))))
                (if scanning-number
                    (begin
                        (set! number-locs (cons (cons current-pos number) number-locs))
                        (set! scanning-number #f)
                        (set! number "")))
                (set! row (+ row 1)))
            lines)
        number-locs))

(define (build-parts lines)
    (let ((part-locs '())
          (row 0))
        (for-each
            (lambda (line)
                (let loop ((col 0))
                    (let ((ch (string-ref line col)))
                        (if (and (not (char-numeric? ch)) (not (char=? ch #\.)))
                            (set! part-locs (cons (cons `(,row ,col) ch) part-locs)))
                        (if (< (+ 1 col) (string-length line))
                            (loop (+ 1 col)))))
                (set! row (+ 1 row)))
            lines)
        part-locs))

(define (check-parts number-locs part-locs)
    (let ((result 0)
          (neighbors '((-1 -1) (-1 0) (-1 1) (0 -1) (0 1) (1 -1) (1 0) (1 1))))
        (for-each
            (lambda (number-loc-entry)
                (let* ((number-loc (car number-loc-entry))
                       (number (cdr number-loc-entry))
                       (number-row (car number-loc))
                       (number-col-first (cadr number-loc))
                       (number-col-last (+ number-col-first (string-length number)))
                       (found #f))
                    (let loop ((number-col number-col-first))
                        (for-each
                            (lambda (neighbor)
                                (let ((adjacent-row (+ number-row (car neighbor)))
                                      (adjacent-col (+ number-col (cadr neighbor))))
                                    (for-each
                                        (lambda (part-loc-entry)
                                            (let* ((part-loc (car part-loc-entry))
                                                   (part-row (car part-loc))
                                                   (part-col (cadr part-loc)))
                                                (if (and (= part-row adjacent-row) (= part-col adjacent-col))
                                                    (set! found #t))))
                                        part-locs)))
                            neighbors)
                        (if (< (+ 1 number-col) number-col-last)
                            (loop (+ 1 number-col))))
                    (if found
                        (set! result (+ result (string->number number))))))
            number-locs)
    result))

(define (process filename)
    (let* ((lines (read-file-into-lines filename))
           (number-locs (build-numbers lines))
           (part-locs (build-parts lines)))
        (check-parts number-locs part-locs)))

(define (main argv)
    (if (< (length argv) 2)
        (prog-usage (car argv))
        (let* ((filename (cadr argv))
               (result (process filename)))
            (display (format "result = ~a" result))
            (newline))))
